version: '3'
services:
  web:
    image: chsilva/rif-exercise
    build: ./
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules/
